version: '3.8'
services:
  rix-api-yanshi:
    image: rixapi/rixapi-pro:latest
    container_name: rix-api-yanshi
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3099:3009"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ALLOW_MULTI_LOGIN_ENABLED=true
      - SQL_DSN=yanshi:rixapipassword@tcp(mysql-yanshi:3306)/yanshi
      - REDIS_CONN_STRING=redis://redis-yanshi/4
      - SESSION_SECRET=RixpOdd13HJsfKHD  # 修改为随机字符串
      - SYNC_FREQUENCY=30
      - BATCH_UPDATE_ENABLED=true
      - GLOBAL_API_RATE_LIMIT=1000000
      - TZ=Asia/Shanghai
    depends_on:
      - redis-yanshi
      - mysql-yanshi
    networks:
      - yanshi-net
  mysql-yanshi:
    image: mysql:8.0
    container_name: mysql-yanshi
    volumes:
      - /data/mysql/data-yanshi:/var/lib/mysql
      - /data/mysql/conf-yanshi:/etc/mysql/conf.d
      - /data/mysql/init-yanshi:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rixapirootpassword
      - MYSQL_DATABASE=yanshi
      - MYSQL_USER=yanshi
      - MYSQL_PASSWORD=rixapipassword
    networks:
      - yanshi-net
  redis-yanshi:
    image: redis:latest
    container_name: redis-yanshi
    restart: always
    volumes:
      - /data/redis/data-yanshi:/data
      - /data/redis/redis-yanshi.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - yanshi-net
networks:
  yanshi-net:
